name: CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install LLVM 21 and CMake
        run: |
          sudo apt-get update
          sudo apt-get install -y wget lsb-release gnupg cmake
          export UBUNTU_CODENAME=jammy
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 21
          sudo apt-get install -y llvm-21-dev libclang-21-dev clang-21

      - name: Configure CMake
        run: cmake -B build -DLLVM_DIR=/usr/lib/llvm-21/lib/cmake/llvm

      - name: Build Project
        run: cmake --build build

      - name: Test Executable
        run: ./build/compiler

      - name: Run Tests
        run: ./build/unit_tests
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/blazejoz/toylang-compiler:latest